//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Sample.Automation.Scheduling.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public long Id { get; private set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public System.DateTime LastModifiedDateTimeUtc { get; set; }
        public short StatusID { get; private set; }
        public short RetryCount { get; private set; }
        public long ScheduleID { get; private set; }
        public System.DateTime StartDateTimeUtc { get; set; }
        public int ToolID { get; set; }
        public string CallbackInfo { get; set; }
        private string ErrorCode { get; set; }
        private string ErrorMsg { get; set; }
    }
}
