//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Sample.Automation.Scheduling.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public long Id { get; set; }
        internal System.DateTime CreatedDateTimeUtc { get; set; }
        internal System.DateTime LastModifiedDateTimeUtc { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDateTimeUtc { get; set; }
        public System.DateTime EndDateTimeUtc { get; set; }
        public Nullable<short> RepeatEvery { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Tool Tool { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
