//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Sample.Automation.Scheduling.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatcher
    {
        public int Id { get; set; }
        public string RequestOrigin { get; set; }
        public System.Guid WorkflowInstanceID { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
