//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Sample.Automation.Scheduling.Engine.Entities
{
    using System;
    
    public enum EngineControl : short
    {
        Shutdown = 0,
        Interrupt = 1,
        Deferred = 2,
        Poll = 3
    }
}
