//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Sample.Automation.Scheduling.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public Tool()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public System.DateTime LastModifiedDateTimeUtc { get; set; }
        public string Name { get; set; }
        public string EndPointAddress { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
